TASK-55972: Add the possibility to delete an ended challenge without announcements
Meeds-io/gamification pull request #314
Opened 2022-04-08 14:46 UTC by GouadriaHanen

Add the Delete option for challenge owners to delete ended challenges without announcements

2022-04-11 15:48 UTC, ahamdi requested changes

2022-04-11 15:48 UTC, ahamdi commented on services/src/main/java/org/exoplatform/addons/gamification/storage/RuleStorage.java
> +import org.jgroups.tests.rt.transports.UdpTransport;
Unneeded import, to remove.

2022-04-11 15:48 UTC, ahamdi commented on challenges-webapp/src/main/webapp/vue-app/challenges/challengesServices.js
> +    method: 'PUT',
Shouldn't we use Delete method ?

2022-04-11 15:48 UTC, ahamdi commented on services/src/main/java/org/exoplatform/addons/gamification/rest/ChallengeRest.java
> +    if (challengeId ==null || challengeId <= 0 ) {
```suggestion
    if (challengeId == null || challengeId <= 0 ) {
```

2022-04-11 15:48 UTC, ahamdi commented on services/src/main/java/org/exoplatform/addons/gamification/storage/RuleStorage.java
> +    if (challengeEntity == null || challengeEntity.getType() == TypeRule.AUTOMATIC || challengeEntity.isDeleted()) {
No need for challengeEntity.isDeleted()

2022-04-11 15:48 UTC, ahamdi commented on services/src/main/java/org/exoplatform/addons/gamification/entities/domain/configuration/RuleEntity.java
> +    @NamedQuery(name = "Rule.findAllChallengesByUser", query = "SELECT DISTINCT r FROM Rule r where r.isDeleted = false AND r.audience in (:ids) order by r.endDate desc") })
Is th eproperty isDeleted still needed ?

2022-04-11 15:48 UTC, ahamdi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengeCard.vue
> +                      <v-list-item-title class="editLabel" @click="confirmDelete">{{ $t('challenges.delete') }}</v-list-item-title>
Wht is the behaviour when you want to delete a challenge that already have announcements ? does it show an error with an i18n message ?

2022-04-12 08:05 UTC, GouadriaHanen commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengeCard.vue
> +                      <v-list-item-title class="editLabel" @click="confirmDelete">{{ $t('challenges.delete') }}</v-list-item-title>
yes it displays an error message: "Error deleting challenge : challenge may have announcements or has not ended yet"

2022-04-12 12:46 UTC, ahamdi approved these changes

2022-04-12 12:48 UTC, merged