TASK-53132: Enable creating and posting announcement challenge with emoji .
Meeds-io/gamification pull request #355
Opened 2022-05-31 13:31 UTC by ArfaouiMohamedAmine

when an emoji is added to the description to announce or to create a challenge, an `sql` error has been endorsed, it turns out that the description (named `COMMENT` ,`EVENT` ,`DESCRIPTION`, `ACTION_TITLE ` in the `GAMIFICATION_RULE`,`GAMIFICATION_ACTIONS_HISTORY` tables) is collated as `utf8`, in order to resolve this issue ; a type modification of utf8mb4 COLLATE `utf8mb4_unicode_ci` and a type change to `varchar`(2000) to support emojis has been added to the `changelog` .

2022-05-31 13:40 UTC, GouadriaHanen requested changes

2022-05-31 13:40 UTC, GouadriaHanen commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-38" author="exo-gamification" dbms="mysql">
changeSet with id 37 has been executed so you have to add a new changeset without removing the last one

2022-05-31 13:40 UTC, GouadriaHanen commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-39" author="exo-gamification" dbms="mysql">
you can add all the modifications in the same changeSet

2022-05-31 13:40 UTC, GouadriaHanen commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-40" author="exo-gamification" dbms="mysql">
same here

2022-05-31 13:40 UTC, GouadriaHanen commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-41" author="exo-gamification" dbms="mysql">
same here

2022-05-31 13:40 UTC, GouadriaHanen commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-42" author="exo-gamification" dbms="mysql">
same here

2022-05-31 16:39 UTC, GouadriaHanen commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-38" author="exo-gamification" dbms="mysql">
as verified in the acceptance DB changelog and acceptance log : changeSet with 37 had not been executed so you can use 37 as id

2022-05-31 16:46 UTC, ArfaouiMohamedAmine commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-39" author="exo-gamification" dbms="mysql">
done !

2022-05-31 16:46 UTC, ArfaouiMohamedAmine commented on services/src/main/resources/db/changelog/gamification.db.changelog-1.0.0.xml
> +    <changeSet id="1.0.0-38" author="exo-gamification" dbms="mysql">
done !

2022-06-01 14:20 UTC, ahamdi approved these changes

2022-06-01 14:22 UTC, merged