MEED-571: enabling administrator view for realizations table from left admin drawer
Meeds-io/gamification pull request #457
Opened 2022-09-09 09:43 UTC by ArfaouiMohamedAmine

This change is going to enable realizations component to detect the Type of the connected user whether it's an Admin or a Regular user when accessed from the left admin drawer .

2022-09-13 17:05 UTC, AzmiTouil requested changes

2022-09-13 17:05 UTC, AzmiTouil commented on portlets/src/main/webapp/WEB-INF/jsp/realizations/index.jsp
> +<%@page import="org.exoplatform.services.security.Identity"%>
useless import!

2022-09-14 08:39 UTC, ArfaouiMohamedAmine commented on portlets/src/main/webapp/WEB-INF/jsp/realizations/index.jsp
> +<%@page import="org.exoplatform.services.security.ConversationState"%>
@AzmiTouil I found that this import is necessary .

2022-09-14 08:45 UTC, AzmiTouil approved these changes

2022-09-14 08:45 UTC, merged