fix: ENGAGEMENT CENTER Improve the display of program card - MEED-707 - Meeds-io/MIPs#13
Meeds-io/gamification pull request #500
Opened 2022-10-04 16:16 UTC by MayTekayaa

Prior to this change, the program card contains only the program cover image, title and points per user.
This change will adjust the display for more visibility by adding the owners program part.

2022-10-05 09:24 UTC, AzmiTouil requested changes

2022-10-05 09:24 UTC, AzmiTouil commented on portlets/src/main/resources/locale/portlet/Challenges_en.properties
> +programs.budget=About {0} per user
should be done in crowdin

2022-10-05 09:24 UTC, AzmiTouil commented on portlets/src/main/resources/locale/portlet/Challenges_en.properties
> +programs.details.label.points=Points
should be done in crowdin

2022-10-05 09:24 UTC, AzmiTouil commented on portlets/src/main/webapp/skin/less/challenges.less
> +  }
Avoid adding news custom classes please!

2022-10-05 09:24 UTC, AzmiTouil commented on portlets/src/main/webapp/vue-app/engagement-center/components/common/AvatarsList.vue
> +      return this.avatars.length;
```suggestion
      return this.avatars?.length;
```

2022-10-05 16:29 UTC, MayTekayaa commented on portlets/src/main/webapp/vue-app/engagement-center/components/common/AvatarsList.vue
> +      return this.avatars.length;
done!

2022-10-05 16:29 UTC, MayTekayaa commented on portlets/src/main/webapp/skin/less/challenges.less
> +  }
done!

2022-10-05 16:29 UTC, MayTekayaa commented on portlets/src/main/resources/locale/portlet/Challenges_en.properties
> +programs.details.label.points=Points
done!

2022-10-05 16:29 UTC, MayTekayaa commented on portlets/src/main/resources/locale/portlet/Challenges_en.properties
> +programs.budget=About {0} per user
done!

2022-10-06 08:27 UTC, AzmiTouil requested changes

2022-10-06 08:27 UTC, AzmiTouil commented on portlets/src/main/webapp/vue-app/engagement-center/components/programs/ProgramOwnersDrawer.vue
> +      displayBackIcon: false,
useless!

2022-10-06 08:27 UTC, AzmiTouil commented on portlets/src/main/webapp/vue-app/engagement-center/components/programs/ProgramOwnersDrawer.vue
> +      this.displayBackIcon = displayBackIcon;
```suggestion
```

2022-10-06 08:27 UTC, AzmiTouil commented on portlets/src/main/webapp/vue-app/engagement-center/components/programs/ProgramCard.vue
> +        :program="program"
```suggestion
```

2022-10-06 08:27 UTC, AzmiTouil commented on portlets/src/main/webapp/vue-app/engagement-center/components/common/AvatarsList.vue
> +      this.$root.$emit('open-drawer', this.avatars);
```suggestion
      this.$root.$emit('open-avatars-drawer', this.avatars);
```

2022-10-06 08:34 UTC, MayTekayaa commented on portlets/src/main/webapp/vue-app/engagement-center/components/common/AvatarsList.vue
> +      this.$root.$emit('open-drawer', this.avatars);
modified!

2022-10-06 08:34 UTC, MayTekayaa commented on portlets/src/main/webapp/vue-app/engagement-center/components/programs/ProgramCard.vue
> +        :program="program"
removed!

2022-10-06 08:34 UTC, MayTekayaa commented on portlets/src/main/webapp/vue-app/engagement-center/components/programs/ProgramOwnersDrawer.vue
> +      this.displayBackIcon = displayBackIcon;
removed!

2022-10-06 08:37 UTC, AzmiTouil approved these changes

2022-10-06 08:48 UTC, merged