feat: Overview Page Add wallet block in rewards portlet - MEED-936 - Meeds-io/MIPs#10
Meeds-io/gamification pull request #590
Opened 2022-11-14 15:56 UTC by MayTekayaa

This change will add the wallet block in the rewards portlet.

2022-11-14 16:26 UTC, AzmiTouil requested changes

2022-11-14 16:26 UTC, AzmiTouil commented on portlets/src/main/webapp/vue-app/myRewards/components/RewardsOverview.vue
> +            <v-icon color="secondary" size="55px">fas fa-wallet</v-icon>
```suggestion
            <v-icon class="secondary--text" size="55">fas fa-wallet</v-icon>
```

2022-11-15 08:09 UTC, MayTekayaa commented on portlets/src/main/webapp/vue-app/myRewards/components/RewardsOverview.vue
> +            <v-icon color="secondary" size="55px">fas fa-wallet</v-icon>
done

2022-11-15 10:51 UTC, AzmiTouil approved these changes

2022-11-15 10:53 UTC, merged