Meeds-io/gatein-portal eat : reorganize application registry list - EXO-61480 - Meeds-io/MPIs#37
Meeds-io/gamification pull request #759
Opened 2023-01-03 15:43 UTC by sofyenne

2023-01-05 15:42 UTC, azayati requested changes

2023-01-05 15:42 UTC, azayati commented on portlets/src/main/webapp/WEB-INF/conf/applicationRegistry/application-registry-configuration.xml
> +    <external-component-plugins>
indentation

2023-01-05 18:09 UTC, sofyenne commented on portlets/src/main/webapp/WEB-INF/conf/applicationRegistry/application-registry-configuration.xml
> +    <external-component-plugins>
done !

2023-01-05 18:10 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 18:12 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-06 11:22 UTC, azayati approved these changes
LGTM

2023-01-06 11:23 UTC, merged